### ISSUE TITLE
[browser extension] Improve search outcomes

### ISSUE THREAD

**Issue by Melodeiro** [volkanakinpasa/Paradify#4]
Spotify fails to search queries with special characters, like "&" which is used for multiple authors. Consider adding an ability to trim unsupported characters, and maybe custom text added by user, for example "original mix"

**Comment by volkanakinpasa** [comment]
Hi Melodeiro,
Thank you for your feedback. Could you please give me some examples?

**Comment by Melodeiro** [comment]
Quite a lot of music with "&" symbol: https://www.youtube.com/watch?v=PbXLivoHOk8 and none of them can be found, until you remove it.

Also i guess, it is safe to remove "feat", sometimes, spotify just have artists separated by only commas: https://www.youtube.com/watch?v=CmxqTkFou0A Another example here is usage "x" instead of "&", which is again could be removed, by a simple rule: if it stays before the "-" and between 2 words. That way "Static X", for example, would search well. Another example, of using the "x": https://www.youtube.com/watch?v=ZDFi-ik2pts

Currently i don't have an example with "original mix" which is missing at spotify, but i guess, that is safe to remove as well, because it is usually a technical prefix, which is just means, it is not remix version.

As i told, if you are not sure about some options, you could just add an option to type anything, the user would like to be removed at the settings. And separating with commas should work well, since spotify succesfully trims them out already

**Comment by volkanakinpasa** [comment]
Hi Melodeiro,
I have fixed the issue with & and feat words. It works now.

for the one with X. It's not easy to remove X between the words atm. I need to find a way and write a regular expression for it.

**Comment by Melodeiro** [comment]
> for the one with X. It's not easy to remove X between the words atm. I need to find a way and write a regular expression for it.

If you don't want to rely on "-" (well, my second example lacks it), i guess, you can use this one: https://regex101.com/r/6Q6MsN/3. Just 2 words (2-20 non-spaces) and " x " between. Just replace the second group with " "

**Comment by akinv** [comment]
I added these words into a list to ignore while searching the tracks. Could you check it out again?

**Comment by volkanakinpasa** [comment]
I added these words into a list to ignore while searching the tracks. Could you check it out again?

**Comment by Melodeiro** [comment]
Only first example, worked on new version, so i did a PR. Feel free to edit: https://github.com/volkanakinpasa/Paradify/pull/6
More details within its description

**Comment by Melodeiro** [comment]
Working fine for now. I hope we will get the better search engine for spotify one day.

**Comment by volkanakinpasa** [comment]
I will change search filter soon with regex which includes all cases
